M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-11-08T17:50:08+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-08T17:50:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X162.433Y-127.254
X173.863Y-127.254
M30
