M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date ke 26. heinäkuuta 2023 21.33.31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-26T21:33:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X162.433Y-127.254
X173.863Y-127.254
T0
M30
